import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    -- Enums
    CREATE TYPE "Role" AS ENUM ('Admin','Repairman');
    CREATE TYPE "ComputerStatus" AS ENUM ('bought','not yet repaired','waiting for parts','repaired waiting for listing','listed','sold','has problems');

    -- Unified users table
    CREATE TABLE IF NOT EXISTS app_user (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        role "Role" NOT NULL,
        deleted BOOLEAN NOT NULL DEFAULT FALSE
    );

    -- Auth
    CREATE TABLE IF NOT EXISTS refresh_token (
        id SERIAL PRIMARY KEY,
        user_id INT NOT NULL,
        token TEXT NOT NULL UNIQUE,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        expires_at TIMESTAMPTZ NOT NULL,
        FOREIGN KEY (user_id) REFERENCES app_user(id)
    );

    -- Domain tables
    CREATE TABLE "makes" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "name" varchar UNIQUE NOT NULL
    );

    CREATE TABLE "models" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "make_id" int NOT NULL,
      "name" varchar NOT NULL
    );

    CREATE TABLE "ram_options" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "label" varchar UNIQUE NOT NULL,
      "gb" int NOT NULL
    );

    CREATE TABLE "ssd_options" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "label" varchar UNIQUE NOT NULL,
      "gb" int NOT NULL
    );

    CREATE TABLE "model_allowed_ram" (
      "model_id" int NOT NULL,
      "ram_option_id" int NOT NULL,
      PRIMARY KEY ("model_id", "ram_option_id")
    );

    CREATE TABLE "model_allowed_ssd" (
      "model_id" int NOT NULL,
      "ssd_option_id" int NOT NULL,
      PRIMARY KEY ("model_id", "ssd_option_id")
    );

    CREATE TABLE "computers" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "model_id" int NOT NULL,
      "ram_option_id" int NOT NULL,
      "ssd_option_id" int NOT NULL,
      "purchase_price" decimal(10,2) NOT NULL,
      "purchase_date" date NOT NULL,
      "sold_price" decimal(10,2),
      "sold_date" date,
      "status" "ComputerStatus" NOT NULL,
      "primary_repairman_id" int,
      "note" text,
      "qr_code" varchar UNIQUE
    );

    CREATE TABLE "computer_repairmen" (
      "computer_id" int NOT NULL,
      "repairman_id" int NOT NULL,
      "assigned_at" timestamp DEFAULT (now()),
      "unassigned_at" timestamp,
      "is_primary" bool DEFAULT false,
      PRIMARY KEY ("computer_id", "repairman_id")
    );

    CREATE TABLE "repairs" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "computer_id" int NOT NULL,
      "repairman_id" int,
      "description" varchar,
      "notes" text,
      "cost" decimal(8,2) NOT NULL DEFAULT 0,
      "hours" decimal(5,2) NOT NULL DEFAULT 0,
      "shipment_id" int,
      "created_at" timestamp DEFAULT (now()),
      "marked_complete" bool NOT NULL DEFAULT false,
      "approved" bool DEFAULT null,
      "admin_id" int,
      "admin_comment" text,
      "approved_at" timestamp
    );

    CREATE TABLE "shipments" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      "tracking_number" varchar UNIQUE NOT NULL,
      "supplier_name" varchar NOT NULL,
      "date_sent" date NOT NULL,
      "date_received" date,
      "cost_send" decimal(8,2) NOT NULL DEFAULT 0,
      "cost_receive" decimal(8,2) NOT NULL DEFAULT 0,
      "note" text
    );

    -- Indexes
    CREATE UNIQUE INDEX ON "models" ("make_id", "name");
    CREATE INDEX ON "computer_repairmen" ("repairman_id");

    -- FKs
    ALTER TABLE "models" ADD FOREIGN KEY ("make_id") REFERENCES "makes" ("id");
    ALTER TABLE "model_allowed_ram" ADD FOREIGN KEY ("model_id") REFERENCES "models" ("id");
    ALTER TABLE "model_allowed_ram" ADD FOREIGN KEY ("ram_option_id") REFERENCES "ram_options" ("id");
    ALTER TABLE "model_allowed_ssd" ADD FOREIGN KEY ("model_id") REFERENCES "models" ("id");
    ALTER TABLE "model_allowed_ssd" ADD FOREIGN KEY ("ssd_option_id") REFERENCES "ssd_options" ("id");
    ALTER TABLE "computers" ADD FOREIGN KEY ("model_id") REFERENCES "models" ("id");
    ALTER TABLE "computers" ADD FOREIGN KEY ("ram_option_id") REFERENCES "ram_options" ("id");
    ALTER TABLE "computers" ADD FOREIGN KEY ("ssd_option_id") REFERENCES "ssd_options" ("id");

    -- Point all former "users" FKs to app_user
    ALTER TABLE "computers" ADD FOREIGN KEY ("primary_repairman_id") REFERENCES "app_user" ("id");
    ALTER TABLE "computer_repairmen" ADD FOREIGN KEY ("computer_id") REFERENCES "computers" ("id");
    ALTER TABLE "computer_repairmen" ADD FOREIGN KEY ("repairman_id") REFERENCES "app_user" ("id");
    ALTER TABLE "repairs" ADD FOREIGN KEY ("computer_id") REFERENCES "computers" ("id");
    ALTER TABLE "repairs" ADD FOREIGN KEY ("repairman_id") REFERENCES "app_user" ("id");
    ALTER TABLE "repairs" ADD FOREIGN KEY ("shipment_id") REFERENCES "shipments" ("id");
    ALTER TABLE "repairs" ADD FOREIGN KEY ("admin_id") REFERENCES "app_user" ("id");
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    DROP TABLE IF EXISTS "repairs";
    DROP TABLE IF EXISTS "computer_repairmen";
    DROP TABLE IF EXISTS "computers";
    DROP TABLE IF EXISTS "model_allowed_ssd";
    DROP TABLE IF EXISTS "model_allowed_ram";
    DROP TABLE IF EXISTS "shipments";
    DROP TABLE IF EXISTS "models";
    DROP TABLE IF EXISTS "makes";
    DROP TABLE IF EXISTS "ram_options";
    DROP TABLE IF EXISTS "ssd_options";

    DROP TABLE IF EXISTS refresh_token;
    DROP TABLE IF EXISTS app_user;

    DROP TYPE IF EXISTS "ComputerStatus";
    DROP TYPE IF EXISTS "Role";
  `);
}